# Generated by Django 6.0 on 2025-12-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookti_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
